name: PyFinance
channels:
  - defaults
dependencies:
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - numpydoc=1.1.0
  - pandas=1.1.5
  - pandas-datareader=0.9.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - xlsxwriter=1.3.7
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - pip
  - pip:
    - yahoofinancials==1.6
prefix: C:\Users\Chris\anaconda3
